# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
notifications:
  email: false
env:
  - JULIA_NUM_THREADS=30
julia:
  - 1.5
  - nightly
jobs:
  allow_failures:
    - julia: nightly
  include:
    - if: branch = master OR tag IS present
      stage: "Documentation"
      julia: 1.4
      os: linux
      # disable global before_script in order not to install Compose twice
      before_script:
      script:
        - |
          julia --color=yes --project=docs/ -e'
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()
            include("docs/make.jl")
          '

after_success:
  # push coverage results to Codecov
  - julia -e 'using Pkg; pkg"add Coverage"; using Coverage; Coveralls.submit(process_folder())'
